#!/usr/bin/env python3
# Copyright 2026 The p2-11 Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

"""mac.py assembles a PDP-11 program and writes it as an OctoGo table.

The programs the emulator carries are written in MACRO-11, in mac/. This script
has the macro11 cross assembler assemble one and writes what comes out as an
array of words with the address it loads at and the address it starts at, for
the emulator to put in memory.

The assembler is not in the repository. scripts/tools.sh fetches and builds
it, into tools/.

Usage: scripts/mac.py [-macro11 DIR] [-o FILE] SOURCE.mac

	-macro11 DIR  where macro11 and dumpobj are (default $MACRO11, or
	              tools/simtools/crossassemblers/macro11)
	-o FILE       where to write the table (default the source's name with
	              .ogo for .mac, beside the source)

A program is one absolute section, .asect, and ends in .end with the address it
starts at. The table of mac/demo.mac is mac.Demo, and the addresses are
mac.DemoAt and mac.DemoStart.
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile


def assemble(tools, source):
    """Answer the bytes of the program by address and where it starts."""
    with tempfile.TemporaryDirectory() as tmp:
        obj = os.path.join(tmp, 'a.obj')
        lst = os.path.join(tmp, 'a.lst')
        try:
            r = subprocess.run([os.path.join(tools, 'macro11'), '-l', lst, '-o', obj, source],
                               capture_output=True, text=True)
        except OSError as e:
            sys.exit('mac.py: %s: %s; scripts/tools.sh builds it' % (tools, e.strerror))
        if r.returncode != 0 or r.stdout.strip() or r.stderr.strip():
            sys.exit('mac.py: %s\n%s%s' % (source, r.stdout, r.stderr))
        listing = open(lst, errors='replace').read()
        r = subprocess.run([os.path.join(tools, 'dumpobj'), obj],
                           capture_output=True, text=True, errors='replace')
        if r.returncode != 0:
            sys.exit('mac.py: %s: dumpobj exited with %d\n%s' % (source, r.returncode, r.stderr))
        dump = r.stdout
    if re.search(r'^\*\*\*', listing, re.M):
        sys.exit('mac.py: %s: the listing has errors\n%s' % (
            source, '\n'.join(l for l in listing.split('\n') if l.startswith('***'))))

    mem = {}
    start = None
    left = 0
    for line in dump.split('\n'):
        m = re.match(r'TEXT ADDR=([0-7]+) LEN=([0-7]+)', line)
        if m:
            left = int(m.group(2), 8)
            continue
        m = re.match(r'\t([0-7]{6}): (.*)', line)
        if m and left:
            a = int(m.group(1), 8)
            here = min(8, left)
            fields = m.group(2).split()
            for i in range(0, here, 2):
                v = int(fields[i // 2], 8)
                mem[a + i] = v & 0o377
                if here - i >= 2:
                    mem[a + i + 1] = v >> 8
            left -= here
            continue
        m = re.match(r'\tInternal displaced ([0-7]+)=([0-7]+)', line)
        if m:
            a, v = int(m.group(1), 8), int(m.group(2), 8)
            v = v - (a + 2) & 0o177777
            mem[a], mem[a + 1] = v & 0o377, v >> 8
            continue
        m = re.match(r'\tXFER \. ABS\.=([0-7]+)', line)
        if m:
            start = int(m.group(1), 8)
            continue
        if re.match(r'\t(Internal|Global|Complex|PSECT|Location counter mod)', line) and \
                not re.match(r'\tPSECT', line):
            sys.exit('mac.py: %s: %s: only a displaced reference is resolved here' %
                     (source, line.strip()))
    if not mem or start is None:
        sys.exit('mac.py: %s: nothing to load, or no .end START' % source)
    return mem, start


def table(name, source, mem, start):
    first = min(mem) & ~1
    last = max(mem) | 1
    words = [mem.get(a, 0) | mem.get(a + 1, 0) << 8 for a in range(first, last, 2)]
    out = [
        '// Copyright 2026 The p2-11 Authors. All rights reserved.',
        '// Use of this source code is governed by a BSD-style',
        '// license that can be found in the LICENSE file.',
        '',
        '// Code generated by scripts/mac.py %s; DO NOT EDIT.' % source,
        '',
        '// %s is the program of %s: %d words that load at %sAt, and it' % (
            name, source, len(words), name),
        '// starts at %sStart.' % name,
        'const (',
        '\t%sAt    = 0o%06o' % (name, first),
        '\t%sStart = 0o%06o' % (name, start),
        ')',
        '',
        'var %s = [...]uint16{' % name,
    ]
    for i in range(0, len(words), 8):
        row = ', '.join('0o%06o' % w for w in words[i:i + 8])
        out.append('\t%s, // %06o' % (row, first + 2 * i))
    out.append('}')
    return '\n'.join(out) + '\n'


def main():
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument('-macro11', default=os.environ.get('MACRO11', 'tools/simtools/crossassemblers/macro11'))
    p.add_argument('-o')
    p.add_argument('-h', '--help', action='store_true')
    p.add_argument('source', nargs='?')
    args = p.parse_args()
    if args.help or not args.source:
        print(__doc__)
        return
    base = os.path.splitext(args.source)[0]
    name = os.path.basename(base).capitalize()
    mem, start = assemble(args.macro11, args.source)
    out = args.o or base + '.ogo'
    new = out + '.new.ogo'
    try:
        with open(new, 'w') as f:
            f.write(table(name, args.source, mem, start))
        subprocess.run(['ogo', 'fmt', '-w', new], check=True)
        os.replace(new, out)
    finally:
        if os.path.exists(new):
            os.unlink(new)


if __name__ == '__main__':
    main()
