#!/usr/bin/env python3
# Copyright 2026 The p2-11 Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

"""rk.py has SimH say what an RK11 does, as a table for the tests.

mac/disk.mac is a program that has the controller do one thing after another
and writes what its registers are after each into a table in memory. This
script assembles it, has the PDP-11/40 of SimH run it with two packs in the
drives 0 and 1 and no other drives, and writes the table as it then is as an
OctoGo table, which the tests compare with what the program leaves in the
machine under test. The table of mac/disk.mac is mac.DiskTable, where it is
in memory is mac.DiskTableAt, and where the program halts mac.DiskHalts.

The packs are made here. A block of one is its own number 128 times, in two
words of which the second has the number of the drive as well.

Neither SimH nor the assembler is in the repository. scripts/tools.sh fetches
and builds them, into tools/.

Usage: scripts/rk.py [-simh PDP11] [-macro11 DIR] [-o FILE] [SOURCE.mac]

	-simh PDP11   the SimH binary (default $SIMH, or tools/simh/BIN/pdp11)
	-macro11 DIR  where macro11 and dumpobj are (default $MACRO11, or
	              tools/simtools/crossassemblers/macro11)
	-o FILE       where to write the table (default the source's name with
	              _table.ogo for .mac, beside the source)

The source is mac/disk.mac unless one is named.
"""

import argparse
import os
import re
import struct
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True  # there is nothing to keep of mac.py
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mac  # noqa: E402

BLOCKS = 4872
TABLE = 0o10000  # where the program has its table
MEMORY = 0o160000
DRIVES = 2


def pack(path, drive):
    with open(path, 'wb') as f:
        for n in range(BLOCKS):
            f.write(struct.pack('<I', n | drive << 16) * 128)


def run(simh, mem, start, tmp):
    lines = ['set cpu 11/40', 'set cpu 256K']  # 248 KB, all an 11/40 can have
    for dev in 'rha ptr ptp lpt dz rl hk rx rp rq tm tq rom'.split():
        lines.append('set %s disabled' % dev)
    for n in range(8):
        if n < DRIVES:
            path = os.path.join(tmp, 'rk%d.dsk' % n)
            pack(path, n)
            lines.append('attach rk%d %s' % (n, path))
        else:
            lines.append('set rk%d disabled' % n)
    lines.append('deposit 0-%o 0' % (MEMORY - 2))
    for a in sorted(mem):
        if a & 1 == 0:
            lines.append('deposit %o %o' % (a, mem[a] | mem.get(a + 1, 0) << 8))
    lines.append('deposit pc %o' % start)
    lines.append('echo #START')
    lines.append('go')
    lines.append('echo #STATE')
    lines.append('examine r5,pc')
    lines.append('echo #TABLE')
    lines.append('examine %o-%o' % (TABLE, TABLE + 0o3776))
    lines.append('echo #END')
    lines.append('exit')
    ini = os.path.join(tmp, 'rk.ini')
    with open(ini, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    try:
        r = subprocess.run([simh, ini], capture_output=True, text=True, errors='replace',
                           timeout=120)
    except subprocess.TimeoutExpired:
        sys.exit('rk.py: SimH did not come to an end')
    except OSError as e:
        sys.exit('rk.py: %s: %s; scripts/tools.sh builds it' % (simh, e.strerror))
    out = r.stdout
    version = re.search(r'^PDP-11 simulator (.*)$', out, re.M)
    if r.returncode != 0 or not version or '#START\n' not in out or '#END' not in out:
        sys.exit('rk.py: SimH exited with %d and said\n%s%s' %
                 (r.returncode, out[-2000:], r.stderr[-2000:]))
    version = re.sub(r'\s+', ' ', version.group(1)).strip()
    body = out.split('#START\n', 1)[1].split('#END', 1)[0]
    stop, rest = body.split('#STATE\n', 1)
    state, table = rest.split('#TABLE\n', 1)
    if 'HALT instruction' not in stop:
        sys.exit('rk.py: the program did not halt: %s' % stop.strip())
    regs = dict(re.findall(r'^(\w+):\s+([0-7]+)', state, re.M))
    end, pc = int(regs['R5'], 8), int(regs['PC'], 8)
    words = {}
    for a, v in re.findall(r'^([0-7]+):\s+([0-7]+)', table, re.M):
        words[int(a, 8)] = int(v, 8)
    if end < TABLE or end - 2 not in words:
        sys.exit('rk.py: the table ends at %o' % end)
    return version, pc, [words[a] for a in range(TABLE, end, 2)]


def table(name, source, version, pc, words):
    out = [
        '// Copyright 2026 The p2-11 Authors. All rights reserved.',
        '// Use of this source code is governed by a BSD-style',
        '// license that can be found in the LICENSE file.',
        '',
        '// Code generated by scripts/rk.py %s; DO NOT EDIT.' % source,
        '',
        '// %sTable is what the program of %s leaves at %sTableAt' % (name, source, name),
        '// when it halts, which is at %sHalts, in the PDP-11/40 of SimH:' % name,
        '// %s.' % version,
        'const (',
        '\t%sTableAt = 0o%06o' % (name, TABLE),
        '\t%sHalts   = 0o%06o' % (name, pc),
        ')',
        '',
        'var %sTable = [...]uint16{' % name,
    ]
    for i in range(0, len(words), 8):
        row = ', '.join('0o%06o' % w for w in words[i:i + 8])
        out.append('\t%s, // %06o' % (row, TABLE + 2 * i))
    out.append('}')
    return '\n'.join(out) + '\n'


def main():
    p = argparse.ArgumentParser(add_help=False)
    p.add_argument('-simh', default=os.environ.get('SIMH', 'tools/simh/BIN/pdp11'))
    p.add_argument('-macro11', default=os.environ.get('MACRO11', 'tools/simtools/crossassemblers/macro11'))
    p.add_argument('-o')
    p.add_argument('-h', '--help', action='store_true')
    p.add_argument('source', nargs='?', default='mac/disk.mac')
    args = p.parse_args()
    if args.help:
        print(__doc__)
        return
    mem, start = mac.assemble(args.macro11, args.source)
    with tempfile.TemporaryDirectory() as tmp:
        version, pc, words = run(args.simh, mem, start, tmp)
    base = os.path.splitext(args.source)[0]
    name = os.path.basename(base).capitalize()
    out = args.o or base + '_table.ogo'
    new = out + '.new.ogo'
    try:
        with open(new, 'w') as f:
            f.write(table(name, args.source, version, pc, words))
        subprocess.run(['ogo', 'fmt', '-w', new], check=True)
        os.replace(new, out)
    finally:
        if os.path.exists(new):
            os.unlink(new)
    print('%d words of table, and the program halts at %06o' % (len(words), pc))


if __name__ == '__main__':
    main()
